Repository FRONTENDSCHOOLPLUS2/Greeny, pull requests merged in 2024-10, with the labels that each got.

#113 refactor: react hook form 적용/무한 스크롤/커스텀 confirm, alert 적용/댓글 작성 시 스크롤 이동
  package.json
  public/images/ResetSearch.svg
  src/app/(greeny)/(home)/page.tsx
  src/app/(greeny)/story/Community.module.scss
  src/app/(greeny)/story/DiarySlider.tsx
  src/app/(greeny)/story/Like.tsx
  src/app/(greeny)/story/PostInfo.tsx
  src/app/(greeny)/story/Search.tsx
  src/app/(greeny)/story/community/DropDown.tsx
  src/app/(greeny)/story/community/Post.module.scss
  src/app/(greeny)/story/community/PostCategory.tsx
  src/app/(greeny)/story/community/PostContent.tsx
  src/app/(greeny)/story/community/PostForm.tsx
  src/app/(greeny)/story/community/PostImage.tsx
  src/app/(greeny)/story/community/ReplyContainer.tsx
  src/app/(greeny)/story/community/ReplyInput.tsx
  src/app/(greeny)/story/community/ReplyItem.tsx
  src/app/(greeny)/story/community/ReplyList.tsx
  src/app/(greeny)/story/community/ReplyModify.tsx
  src/app/(greeny)/story/community/SearchAndWrite.tsx
  src/app/(greeny)/story/community/SubMenu.tsx
  src/app/(greeny)/story/community/[id]/SubMenuContainer.tsx
  src/app/(greeny)/story/community/[id]/page.tsx
  src/app/(greeny)/story/diaries/DiaryItem.tsx
  src/app/(greeny)/story/diaries/DiaryList.tsx
  src/app/(greeny)/story/diaries/[id]/DiarySubMenu.tsx
  src/app/(greeny)/story/diaries/[id]/FollowBtn.tsx
  src/app/(greeny)/story/diaries/[id]/page.tsx
  src/app/(greeny)/story/diaries/page.tsx
  src/app/api/actions/postAction.ts
  src/app/api/fetch/postFetch.ts
  src/components/modal/Modal.module.scss
  src/contexts/ReplyContext.tsx
  src/hooks/useInView.tsx
  src/hooks/useInfiniteFetch.tsx
  src/types/plant.ts
  src/utils/confirm.ts
  yarn.lock
Labels: 기능, 리팩터링

#114 deploy : 9차 배포
  package.json
  public/images/ResetSearch.svg
  src/app/(greeny)/(home)/page.tsx
  src/app/(greeny)/story/Community.module.scss
  src/app/(greeny)/story/DiarySlider.tsx
  src/app/(greeny)/story/Like.tsx
  src/app/(greeny)/story/PostInfo.tsx
  src/app/(greeny)/story/Search.tsx
  src/app/(greeny)/story/community/DropDown.tsx
  src/app/(greeny)/story/community/Post.module.scss
  src/app/(greeny)/story/community/PostCategory.tsx
  src/app/(greeny)/story/community/PostContent.tsx
  src/app/(greeny)/story/community/PostForm.tsx
  src/app/(greeny)/story/community/PostImage.tsx
  src/app/(greeny)/story/community/ReplyContainer.tsx
  src/app/(greeny)/story/community/ReplyInput.tsx
  src/app/(greeny)/story/community/ReplyItem.tsx
  src/app/(greeny)/story/community/ReplyList.tsx
  src/app/(greeny)/story/community/ReplyModify.tsx
  src/app/(greeny)/story/community/SearchAndWrite.tsx
  src/app/(greeny)/story/community/SubMenu.tsx
  src/app/(greeny)/story/community/[id]/SubMenuContainer.tsx
  src/app/(greeny)/story/community/[id]/page.tsx
  src/app/(greeny)/story/diaries/DiaryItem.tsx
  src/app/(greeny)/story/diaries/DiaryList.tsx
  src/app/(greeny)/story/diaries/[id]/DiarySubMenu.tsx
  src/app/(greeny)/story/diaries/[id]/FollowBtn.tsx
  src/app/(greeny)/story/diaries/[id]/page.tsx
  src/app/(greeny)/story/diaries/page.tsx
  src/app/api/actions/postAction.ts
  src/app/api/fetch/postFetch.ts
  src/components/modal/Modal.module.scss
  src/contexts/ReplyContext.tsx
  src/hooks/useInView.tsx
  src/hooks/useInfiniteFetch.tsx
  src/types/plant.ts
  src/utils/confirm.ts
  yarn.lock
Labels: 리팩터링, 배포

#115 docs: README 수정
  README.md
Labels: 문서 작업

#117 docs: README 수정
  README.md
Labels: 문서 작업

#118 docs: README 수정
  README.md
Labels: 문서 작업
