Repository FRONTENDSCHOOLPLUS2/Greeny, pull requests merged in 2024-09, with the labels that each got.

#98 styles: 식물 이야기 반응형
  src/app/(greeny)/(home)/Home.module.scss
  src/app/(greeny)/story/Community.module.scss
  src/app/(greeny)/story/DiarySwiper.tsx
  src/app/(greeny)/story/ImageModal.tsx
  src/app/(greeny)/story/PostItem.tsx
  src/app/(greeny)/story/PostLayout.tsx
  src/app/(greeny)/story/_storyMixin.scss
  src/app/(greeny)/story/community/Post.module.scss
  src/app/(greeny)/story/community/ReplyInput.tsx
  src/app/(greeny)/story/community/SearchAndWrite.tsx
  src/app/(greeny)/story/community/[id]/page.tsx
  src/app/(greeny)/story/community/new/page.tsx
  src/app/(greeny)/story/community/page.tsx
  src/app/(greeny)/story/diaries/Diary.module.scss
  src/app/(greeny)/story/diaries/DiaryItem.tsx
  src/app/(greeny)/story/diaries/[id]/DiaryDetail.module.scss
  src/app/(greeny)/story/diaries/[id]/DiaryImageSlider.tsx
  src/app/(greeny)/story/diaries/[id]/page.tsx
  src/app/(greeny)/story/diaries/page.tsx
  src/app/(greeny)/story/layout.tsx
  src/app/api/fetch/postFetch.ts
  src/hooks/useCheckViewportWidthByThreshold.tsx
  src/hooks/useImageModal.tsx
  src/types/plant.ts
Labels: UI 작업

#100 styles: 식물 이야기 반응형, 홈 페이지 스토리 리스트 컴포넌트 사용
  src/app/(greeny)/(home)/Home.module.scss
  src/app/(greeny)/(home)/page.tsx
  src/app/(greeny)/story/Community.module.scss
  src/app/(greeny)/story/PostList.tsx
  src/app/(greeny)/story/community/Post.module.scss
  src/app/(greeny)/story/community/PostForm.tsx
Labels: UI 작업

#101 styles: 나의 식물 페이지 반응형 작업
  public/images/PhotoAddIcon.svg
  src/app/(greeny)/(home)/Home.module.scss
  src/app/(greeny)/plant/MyPlant.module.scss
  src/app/(greeny)/plant/[id]/MyPlantDetail.module.scss
  src/app/(greeny)/plant/[id]/diaryEdit/DiaryEditForm.tsx
  src/app/(greeny)/plant/[id]/diaryNew/DiaryNewForm.tsx
  src/app/(greeny)/plant/[id]/diaryNew/MyPlantDiaryNew.module.scss
  src/app/(greeny)/plant/new/MyPlantAddForm.tsx
  src/app/(user)/signup/SignUpForm.tsx
  src/app/(user)/signup/Signup.module.scss
Labels: UI 작업

#102 styles: 마이페이지, 식물백과 반응형 작업
  src/app/(greeny)/books/CardItem.tsx
  src/app/(greeny)/books/CardList.module.scss
  src/app/(greeny)/books/UI.module.scss
  src/app/(greeny)/books/[cntntsNo]/page.tsx
  src/app/(greeny)/profile/PlantThumbnail.tsx
  src/app/(greeny)/profile/Profile.module.scss
  src/app/(greeny)/profile/Profile.tsx
  src/app/(greeny)/profile/[_id]/DeleteButton.tsx
  src/app/(greeny)/profile/[_id]/page.module.scss
  src/app/(greeny)/profile/[_id]/page.tsx
  src/app/(greeny)/profile/[_id]/plant/DeleteButton.module.scss
  src/app/(greeny)/profile/[_id]/plant/PageTemplate.module.scss
  src/app/(greeny)/profile/[_id]/user/PageTemplate.module.scss
  src/app/(greeny)/profile/bookmark/BookmarkPlant.tsx
  src/app/(greeny)/profile/bookmark/PageTemplate.module.scss
  src/app/(greeny)/profile/bookmark/PageTemplate.tsx
  src/app/(greeny)/profile/detail/page.module.scss
  src/app/(greeny)/profile/edit/Edit.module.scss
  src/app/(greeny)/profile/edit/EditForm.tsx
  src/app/(greeny)/profile/page.module.scss
Labels: UI 작업

#103 styles: include mobile 방식으로 변경
  src/app/(greeny)/books/CardItem.module.scss
  src/app/(greeny)/books/Filter.module.scss
  src/app/(greeny)/books/Modal.module.scss
  src/app/(greeny)/books/UI.module.scss
  src/app/(greeny)/books/[cntntsNo]/page.module.scss
  src/app/(greeny)/profile/Follow.module.scss
  src/app/(greeny)/profile/Heading.module.scss
  src/app/(greeny)/profile/PlantList.module.scss
  src/app/(greeny)/profile/PlantThumbnail.module.scss
  src/app/(greeny)/profile/PostList.module.scss
  src/app/(greeny)/profile/Profile.module.scss
  src/app/(greeny)/profile/[_id]/page.module.scss
  src/app/(greeny)/profile/[_id]/plant/PageTemplate.module.scss
  src/app/(greeny)/profile/[_id]/plant/Plant.module.scss
  src/app/(greeny)/profile/[_id]/user/DeleteButton.module.scss
  src/app/(greeny)/profile/[_id]/user/PageTemplate.module.scss
  src/app/(greeny)/profile/[_id]/user/User.module.scss
  src/app/(greeny)/profile/bookmark/BookmarkPlant.module.scss
  src/app/(greeny)/profile/bookmark/PageTemplate.module.scss
  src/app/(greeny)/profile/detail/page.module.scss
  src/app/(greeny)/profile/edit/Edit.module.scss
  src/app/(greeny)/profile/page.module.scss
Labels: UI 작업

#107 feat: 커스텀 confirm, alert/게시글 수정/DropDown 스타일 수정/커스텀 훅 리팩터링
  src/app/(greeny)/layout.tsx
  src/app/(greeny)/story/Community.module.scss
  src/app/(greeny)/story/community/Post.module.scss
  src/app/(greeny)/story/community/PostCategory.tsx
  src/app/(greeny)/story/community/PostContent.tsx
  src/app/(greeny)/story/community/PostForm.tsx
  src/app/(greeny)/story/community/PostImage.tsx
  src/app/(greeny)/story/community/[id]/edit/PostFormEdit.tsx
  src/app/(greeny)/story/community/[id]/edit/page.tsx
  src/app/(greeny)/story/community/new/page.tsx
  src/app/(user)/layout.tsx
  src/app/api/actions/postAction.ts
  src/components/modal/Modal.module.scss
  src/components/modal/ModalAlert.tsx
  src/components/modal/ModalConfirm.tsx
  src/contexts/ModalContext.tsx
  src/hooks/useCheckViewportWidthByThreshold.tsx
  src/hooks/useFocusTrap.tsx
  src/hooks/useModal.tsx
Labels: 기능, 리팩터링, UI 작업

#109 cont: mbit 테스트 페이지 작업중
  src/app/(no_layout)/error.tsx
  src/app/(no_layout)/event/event.module.scss
  src/app/(no_layout)/event/page.tsx
  src/app/(no_layout)/event/plantTest/PlantText.tsx
  src/app/(no_layout)/event/plantTest/page.tsx
  src/app/(no_layout)/layout.tsx
  src/app/(no_layout)/loading.tsx
  src/app/(no_layout)/login/Login.module.scss
  src/app/(no_layout)/login/LoginForm.tsx
  src/app/(no_layout)/login/page.tsx
  src/app/(no_layout)/signup/SignUpForm.tsx
  src/app/(no_layout)/signup/Signup.module.scss
  src/app/(no_layout)/signup/page.tsx
  src/app/data/questionList.ts
  src/app/data/resultList.ts
  src/types/event.ts
Labels: 기능, 리팩터링
