Repository FRONTENDSCHOOLPLUS2/Greeny, pull requests merged in 2024-08, with the labels that each got.

#30 게시글 리스트 조회, 게시글 상세 페이지 댓글 조회
  package.json
  src/QueryProvider.tsx
  src/app/(greeny)/layout.tsx
  src/app/(greeny)/story/Community.module.scss
  src/app/(greeny)/story/PostItem.tsx
  src/app/(greeny)/story/PostList.tsx
  src/app/(greeny)/story/community/Post.module.scss
  src/app/(greeny)/story/community/ReplyItem.tsx
  src/app/(greeny)/story/community/ReplyList.tsx
  src/app/(greeny)/story/community/SubMenu.tsx
  src/app/(greeny)/story/community/[id]/page.tsx
Labels: 기능

#39 feat: 식물 백과 조회 기능
  src/app/(greeny)/books/@modal/(.)search/Search.module.scss
  src/app/(greeny)/books/@modal/(.)search/default.tsx
  src/app/(greeny)/books/@modal/(.)search/page.tsx
  src/app/(greeny)/books/Books.module.scss
  src/app/(greeny)/books/Modal.module.scss
  src/app/(greeny)/books/Modal.tsx
  src/app/(greeny)/books/[cntntsNo]/[cntntsNo].module.scss
  src/app/(greeny)/books/[cntntsNo]/page.tsx
  src/app/(greeny)/books/[idx]/[idx].module.scss
  src/app/(greeny)/books/page.tsx
  src/app/(greeny)/books/search/Search.module.scss
  src/app/(greeny)/books/search/page.tsx
  src/app/data/plantList.json
  src/components/modal/Modal.module.scss
  yarn.lock
Labels: 기능

#40 feat:로그인/회원가입 기능 완료
  auth.d.ts
  package.json
  src/app/(greeny)/(home)/page.tsx
  src/app/(user)/login/Login.module.scss
  src/app/(user)/login/LoginForm.tsx
  src/app/(user)/login/page.tsx
  src/app/(user)/signup/SignUpForm.tsx
  src/app/(user)/signup/page.tsx
  src/app/api/actions/authAction.ts
  src/app/api/actions/useAction.ts
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/fetch/postFetch.ts
  src/auth.ts
  src/components/button/Button.module.scss
  src/components/button/Button.tsx
  src/middleware.ts
  src/styles/reset.css
  src/types/image.ts
  src/types/user.ts
  yarn.lock
Labels: 기능

#43 feat: 다이어리 리스트, 피드, 상세 페이지 조회/상세 페이지 이미지 슬라이더, 모달/fetch 로직 리팩터링
  src/app/(greeny)/(home)/page.tsx
  src/app/(greeny)/story/Community.module.scss
  src/app/(greeny)/story/DiarySlider.tsx
  src/app/(greeny)/story/DiarySwiper.tsx
  src/app/(greeny)/story/ImageItem.tsx
  src/app/(greeny)/story/ImageModal.tsx
  src/app/(greeny)/story/ImageSlider.tsx
  src/app/(greeny)/story/PostList.tsx
  src/app/(greeny)/story/community/Post.module.scss
  src/app/(greeny)/story/community/ReplyItem.tsx
  src/app/(greeny)/story/community/ReplyList.tsx
  src/app/(greeny)/story/community/[id]/page.tsx
  src/app/(greeny)/story/community/page.tsx
  src/app/(greeny)/story/diaries/Diary.module.scss
  src/app/(greeny)/story/diaries/DiaryItem.tsx
  src/app/(greeny)/story/diaries/DiaryList.tsx
  src/app/(greeny)/story/diaries/[id]/DiaryDetail.module.scss
  src/app/(greeny)/story/diaries/[id]/DiaryImageSlider.tsx
  src/app/(greeny)/story/diaries/[id]/page.tsx
  src/app/(greeny)/story/diaries/page.tsx
  src/app/(greeny)/story/page.tsx
  src/app/api/fetch/postFetch.ts
Labels: 기능, 리팩터링

#45 feat: 나의 식물 추가하기
  api/dbinit/team/data.js
  api/dbinit/team/uploadFiles/alocasia.webp
  api/dbinit/team/uploadFiles/caladium.jpg
  api/dbinit/team/uploadFiles/camellia.webp
  api/dbinit/team/uploadFiles/clivia.jpg
  api/dbinit/team/uploadFiles/dizygotheca.webp
  api/dbinit/team/uploadFiles/dracaena.webp
  api/dbinit/team/uploadFiles/rohdea.jpg
  api/dbinit/team/uploadFiles/sansevieria.jpg
  api/dbinit/team/uploadFiles/syngonium.jpg
  api/dbinit/team/uploadFiles/zamiya.jpg
  package.json
  public/images/PhotoAddIcon.svg
  src/app/(greeny)/(home)/(section)/TodayPlant.tsx
  src/app/(greeny)/books/[cntntsNo]/page.tsx
  src/app/(greeny)/books/page.tsx
  src/app/(greeny)/myplant/MyPlant.module.scss
  src/app/(greeny)/myplant/[id]/MyPlantDetail.module.scss
  src/app/(greeny)/myplant/[id]/PlantDetail.tsx
  src/app/(greeny)/myplant/[id]/PlantDiary.tsx
  src/app/(greeny)/myplant/[id]/PlantInfo.tsx
  src/app/(greeny)/myplant/[id]/diaryAdd/MyPlantDiaryAdd.module.scss
  src/app/(greeny)/myplant/[id]/diaryAdd/page.tsx
  src/app/(greeny)/myplant/[id]/page.tsx
  src/app/(greeny)/myplant/new/MyPlantAddForm.tsx
  src/app/(greeny)/myplant/new/MyPlantNew.module.scss
  src/app/(greeny)/myplant/new/page.tsx
  src/app/(greeny)/myplant/page.tsx
  src/app/(user)/login/Login.module.scss
  src/app/(user)/signup/SignUpForm.tsx
  src/app/(user)/signup/Signup.module.scss
  src/app/api/fetch/plantFetch.ts
  src/app/data/plantList.json
  src/app/data/plantList.ts
  src/components/button/Button.module.scss
  src/styles/reset.css
  src/types/plant.ts
  yarn.lock
Labels: 기능

#47 feat: 마이페이지 프로필 조회 기능
  .husky/pre-push
  package.json
  src/app/(greeny)/myplant/(calendar)/Calendar.module.scss
  src/app/(greeny)/profile/Profile.module.scss
  src/app/(greeny)/profile/Tab.module.scss
  src/app/(greeny)/profile/Tab.tsx
  src/app/(greeny)/profile/follower/Follower.module.scss
  src/app/(greeny)/profile/follower/page.tsx
  src/app/(greeny)/profile/following/ClientButton.tsx
  src/app/(greeny)/profile/following/ClientForm.tsx
  src/app/(greeny)/profile/following/Following.module.scss
  src/app/(greeny)/profile/following/page.tsx
  src/app/(greeny)/profile/page.tsx
  src/app/api/actions/followAction.ts
  src/components/Input.module.scss
  src/components/Input.tsx
  src/styles/variable.css
  src/types/follow.ts
  src/types/plant.ts
  yarn.lock
Labels: 기능

#50 feat:식물 다이어리 조회 기능
  api/dbinit/team/data.js
  package.json
  public/images/CaleandarIcon.svg
  src/app/(greeny)/myplant/(calendar)/Calendar.module.scss
  src/app/(greeny)/myplant/(calendar)/Calendar.tsx
  src/app/(greeny)/myplant/[id]/Calendar.scss
  src/app/(greeny)/myplant/[id]/MyPlantDetail.module.scss
  src/app/(greeny)/myplant/[id]/PlantDetail.tsx
  src/app/(greeny)/myplant/[id]/PlantDiary.tsx
  src/app/(greeny)/myplant/[id]/page.tsx
  src/app/(greeny)/myplant/new/MyPlantAddForm.tsx
  src/app/(greeny)/myplant/page.tsx
  src/app/(greeny)/profile/Tab.tsx
  src/app/api/fetch/plantFetch.ts
  src/app/api/fetch/userFetch.ts
  src/auth.ts
  src/types/plant.ts
  src/types/response.ts
  yarn.lock
Labels: 기능

#51 feat: 게시글 및 댓글 기능
  src/app/(greeny)/story/Community.module.scss
  src/app/(greeny)/story/community/DropDown.tsx
  src/app/(greeny)/story/community/Post.module.scss
  src/app/(greeny)/story/community/PostForm.tsx
  src/app/(greeny)/story/community/PostNew.tsx
  src/app/(greeny)/story/community/ReplyInput.tsx
  src/app/(greeny)/story/community/ReplyItem.tsx
  src/app/(greeny)/story/community/ReplyList.tsx
  src/app/(greeny)/story/community/ReplyModify.tsx
  src/app/(greeny)/story/community/SearchAndWrite.tsx
  src/app/(greeny)/story/community/SubMenu.tsx
  src/app/(greeny)/story/community/[id]/SubMenuContainer.tsx
  src/app/(greeny)/story/community/[id]/page.tsx
  src/app/(greeny)/story/community/new/page.tsx
  src/app/api/actions/postAction.ts
  src/components/UserProfile.tsx
  src/types/post.ts
Labels: 기능, UI 작업

#61 feat: 마이페이지 식물/사용자 북마크 삭제, 상세 페이지, 팔로우 식물 개수, 목록 조회, 검색, 삭제, 나의 작성글 목록
  src/app/(greeny)/profile/Follow.module.scss
  src/app/(greeny)/profile/Profile.module.scss
  src/app/(greeny)/profile/Tab.module.scss
  src/app/(greeny)/profile/Tab.tsx
  src/app/(greeny)/profile/[[..._id]]/AddButton.tsx
  src/app/(greeny)/profile/[[..._id]]/page.tsx
  src/app/(greeny)/profile/detail/Detail.module.scss
  src/app/(greeny)/profile/detail/page.tsx
  src/app/(greeny)/profile/edit/EditForm.tsx
  src/app/(greeny)/profile/follower/page.tsx
  src/app/(greeny)/profile/following/FollowingListWrapper.tsx
  src/app/(greeny)/profile/following/PageTemplate.tsx
  src/app/(greeny)/profile/following/User.tsx
  src/app/(greeny)/profile/following/page.tsx
  src/app/(greeny)/profile/page.tsx
  src/app/(greeny)/profile/plant/DeleteButton.tsx
  src/app/(greeny)/profile/plant/PageTemplate.tsx
  src/app/(greeny)/profile/plant/Plant.module.scss
  src/app/(greeny)/profile/plant/Plant.tsx
  src/app/(greeny)/profile/plant/PlantForm.tsx
  src/app/(greeny)/profile/plant/PlantListWrapper.tsx
  src/app/(greeny)/profile/plant/page.tsx
  src/app/(greeny)/profile/user/DeleteButton.tsx
  src/app/(greeny)/profile/user/PageTemplate.tsx
  src/app/(greeny)/profile/user/User.module.scss
  src/app/(greeny)/profile/user/User.tsx
  src/app/(greeny)/profile/user/UserForm.tsx
  src/app/(greeny)/profile/user/UserListWrapper.tsx
  src/app/(greeny)/profile/user/page.tsx
  src/app/api/actions/followAction.ts
  src/components/layout/Header.tsx
  src/types/bookmark.ts
  src/types/follow.ts
  src/types/plant.ts
  src/types/response.ts
  src/types/user.ts
Labels: 기능, UI 작업

#62 feat: 검색, 페이지네이션, 파일 추가 및 파일 이름 변경, 식물 팔로우, 게시글 좋아요, 배너 순서 수정, 각종 버그 수정
  public/images/LikeIcon_nor.svg
  public/images/LikeIcon_sel.svg
  src/app/(greeny)/(home)/(section)/Banner.tsx
  src/app/(greeny)/(home)/page.tsx
  src/app/(greeny)/profile/Tab.tsx
  src/app/(greeny)/profile/detail/page.tsx
  src/app/(greeny)/story/Community.module.scss
  src/app/(greeny)/story/Like.tsx
  src/app/(greeny)/story/NoResult.tsx
  src/app/(greeny)/story/PageHeading.tsx
  src/app/(greeny)/story/Pagination.tsx
  src/app/(greeny)/story/PostInfo.tsx
  src/app/(greeny)/story/PostItem.tsx
  src/app/(greeny)/story/PostList.tsx
  src/app/(greeny)/story/Search.tsx
  src/app/(greeny)/story/community/Categories.tsx
  src/app/(greeny)/story/community/PostForm.tsx
  src/app/(greeny)/story/community/[id]/page.tsx
  src/app/(greeny)/story/community/page.tsx
  src/app/(greeny)/story/diaries/DiaryItem.tsx
  src/app/(greeny)/story/diaries/DiaryList.tsx
  src/app/(greeny)/story/diaries/NoResultDiary.tsx
  src/app/(greeny)/story/diaries/[id]/DiarySubMenu.tsx
  src/app/(greeny)/story/diaries/[id]/FollowBtn.tsx
  src/app/(greeny)/story/diaries/[id]/page.tsx
  src/app/(greeny)/story/diaries/page.tsx
  src/app/(greeny)/story/page.tsx
  src/app/api/actions/postAction.ts
  src/app/api/fetch/postFetch.ts
  src/types/plant.ts
  src/types/post.ts
Labels: 버그, 기능

#64 feat: 마이페이지 - 북마크 기능
  src/app/(greeny)/profile/bookmark/Bookmark.module.scss
  src/app/(greeny)/profile/bookmark/PageTemplate.tsx
  src/app/(greeny)/profile/bookmark/Tab.module.scss
  src/app/(greeny)/profile/bookmark/Tab.tsx
  src/app/(greeny)/profile/bookmark/page.tsx
  src/app/(greeny)/profile/plant/Plant.tsx
  src/app/(greeny)/profile/plant/PlantListWrapper.tsx
  src/app/(greeny)/profile/user/User.tsx
  src/app/(greeny)/profile/user/UserListWrapper.tsx
  src/app/api/actions/followAction.ts
  src/app/api/actions/useAction.ts
  src/types/bookmark.ts
Labels: 기능

#67 feat: 일기, 게시글 북마크 추가 요청 시 content 보냄, 일기 상세 페이지 UI 변경, 식물 프로필 경로 변경
  src/app/(greeny)/story/Like.tsx
  src/app/(greeny)/story/PostInfo.tsx
  src/app/(greeny)/story/diaries/DiaryItem.tsx
  src/app/(greeny)/story/diaries/[id]/DiaryDetail.module.scss
  src/app/(greeny)/story/diaries/[id]/DiarySubMenu.tsx
  src/app/(greeny)/story/diaries/[id]/FollowBtn.tsx
  src/app/(greeny)/story/diaries/[id]/page.tsx
  src/app/api/actions/postAction.ts
  src/types/plant.ts
Labels: 기능, UI 작업

#68 fix: 마이페이지 - 탭메뉴 401 Unauthorized 에러 수정, 탭메뉴 공통 컴포넌트화
  src/app/(greeny)/profile/PlantThumbnail.tsx
  src/app/(greeny)/profile/Profile.module.scss
  src/app/(greeny)/profile/Tab.module.scss
  src/app/(greeny)/profile/Tab.tsx
  src/app/(greeny)/profile/[[..._id]]/page.tsx
  src/app/(greeny)/profile/bookmark/PageTemplate.tsx
  src/app/(greeny)/profile/detail/Detail.module.scss
  src/components/Tab.module.scss
  src/components/Tab.tsx
Labels: QA/QC, 리팩터링

#69 feat : 식물 팔로우 기능 추가
  src/app/(greeny)/myplant/[id]/FollowButton.tsx
  src/app/(greeny)/myplant/[id]/MyPlantDetail.module.scss
  src/app/(greeny)/myplant/[id]/PlantDetail.tsx
  src/app/(greeny)/myplant/[id]/PlantDiary.tsx
  src/app/(greeny)/myplant/[id]/PlantInfo.tsx
  src/app/(greeny)/myplant/[id]/diaryNew/DiaryNewForm.tsx
  src/app/(greeny)/myplant/[id]/edit/MyPlantEditForm.tsx
  src/app/(greeny)/myplant/[id]/page.tsx
  src/app/(greeny)/myplant/new/MyPlantAddForm.tsx
  src/app/(greeny)/myplant/page.tsx
  src/app/(greeny)/profile/bookmark/PageTemplate.tsx
  src/app/(greeny)/profile/edit/EditForm.tsx
  src/app/(user)/signup/SignUpForm.tsx
  src/app/api/actions/followAction.ts
  src/app/api/actions/plantAction.ts
  src/app/api/actions/userAction.ts
  src/app/api/fetch/plantFetch.ts
  src/auth.ts
  src/components/layout/Footer.tsx
  src/middleware.ts
Labels: 기능

#70 4차 배포
  src/app/(greeny)/myplant/[id]/FollowButton.tsx
  src/app/(greeny)/myplant/[id]/MyPlantDetail.module.scss
  src/app/(greeny)/myplant/[id]/PlantDetail.tsx
  src/app/(greeny)/myplant/[id]/PlantDiary.tsx
  src/app/(greeny)/myplant/[id]/PlantInfo.tsx
  src/app/(greeny)/myplant/[id]/diaryNew/DiaryNewForm.tsx
  src/app/(greeny)/myplant/[id]/edit/MyPlantEditForm.tsx
  src/app/(greeny)/myplant/[id]/page.tsx
  src/app/(greeny)/myplant/new/MyPlantAddForm.tsx
  src/app/(greeny)/myplant/page.tsx
  src/app/(greeny)/profile/PlantThumbnail.tsx
  src/app/(greeny)/profile/Profile.module.scss
  src/app/(greeny)/profile/Tab.module.scss
  src/app/(greeny)/profile/Tab.tsx
  src/app/(greeny)/profile/[[..._id]]/page.tsx
  src/app/(greeny)/profile/bookmark/Bookmark.module.scss
  src/app/(greeny)/profile/bookmark/PageTemplate.tsx
  src/app/(greeny)/profile/bookmark/page.tsx
  src/app/(greeny)/profile/detail/Detail.module.scss
  src/app/(greeny)/profile/edit/EditForm.tsx
  src/app/(greeny)/profile/plant/Plant.tsx
  src/app/(greeny)/profile/plant/PlantListWrapper.tsx
  src/app/(greeny)/profile/user/User.tsx
  src/app/(greeny)/profile/user/UserListWrapper.tsx
  src/app/(greeny)/story/Like.tsx
  src/app/(greeny)/story/PostInfo.tsx
  src/app/(greeny)/story/diaries/DiaryItem.tsx
  src/app/(greeny)/story/diaries/[id]/DiaryDetail.module.scss
  src/app/(greeny)/story/diaries/[id]/DiarySubMenu.tsx
  src/app/(greeny)/story/diaries/[id]/FollowBtn.tsx
  src/app/(greeny)/story/diaries/[id]/page.tsx
  src/app/(user)/signup/SignUpForm.tsx
  src/app/api/actions/followAction.ts
  src/app/api/actions/plantAction.ts
  src/app/api/actions/postAction.ts
  src/app/api/actions/userAction.ts
  src/app/api/fetch/plantFetch.ts
  src/auth.ts
  src/components/Tab.module.scss
  src/components/Tab.tsx
  src/components/layout/Footer.tsx
  src/middleware.ts
  src/types/bookmark.ts
  src/types/plant.ts
Labels: 배포

#74 fix: 마이페이지 - 타인의 프로필 페이지에서 그 타인의 식물, 포스트를 탭메뉴에서 보여주도록 수정
  src/app/(greeny)/profile/[[..._id]]/page.tsx
  src/app/(greeny)/profile/bookmark/PageTemplate.tsx
  src/app/api/actions/postAction.ts
  src/types/bookmark.ts
Labels: 버그, QA/QC

#77 fix: 식물 이야기 1차 QA 완료
  src/app/(greeny)/story/Community.module.scss
  src/app/(greeny)/story/DiarySwiper.tsx
  src/app/(greeny)/story/ImageSlider.tsx
  src/app/(greeny)/story/community/Post.module.scss
  src/app/(greeny)/story/diaries/DiaryItem.tsx
  src/app/(greeny)/story/diaries/[id]/DiaryImageSlider.tsx
  src/hooks/useImageModal.tsx
Labels: QA/QC

#78 fix: 식집사 삭제 시 /profile/user로 가면서 0번 정보가 나오는 문제 수정 외
  src/app/(greeny)/books/page.tsx
  src/app/(greeny)/profile/PlantThumbnail.tsx
  src/app/(greeny)/profile/Profile.module.scss
  src/app/(greeny)/profile/[_id]/AddButton.tsx
  src/app/(greeny)/profile/[_id]/page.tsx
  src/app/(greeny)/profile/[_id]/plant/DeleteButton.tsx
  src/app/(greeny)/profile/[_id]/plant/PageTemplate.tsx
  src/app/(greeny)/profile/[_id]/plant/Plant.module.scss
  src/app/(greeny)/profile/[_id]/plant/Plant.tsx
  src/app/(greeny)/profile/[_id]/plant/PlantForm.tsx
  src/app/(greeny)/profile/[_id]/plant/PlantListWrapper.tsx
  src/app/(greeny)/profile/[_id]/plant/page.tsx
  src/app/(greeny)/profile/[_id]/user/DeleteButton.tsx
  src/app/(greeny)/profile/[_id]/user/PageTemplate.tsx
  src/app/(greeny)/profile/[_id]/user/User.module.scss
  src/app/(greeny)/profile/[_id]/user/User.tsx
  src/app/(greeny)/profile/[_id]/user/UserForm.tsx
  src/app/(greeny)/profile/[_id]/user/UserListWrapper.tsx
  src/app/(greeny)/profile/[_id]/user/page.tsx
  src/app/(greeny)/profile/detail/page.tsx
  src/app/(greeny)/profile/page.tsx
  src/app/(greeny)/profile/plant/PlantListWrapper.tsx
  src/app/api/actions/followAction.ts
  src/app/api/actions/postAction.ts
  src/app/api/actions/userAction.ts
Labels: 버그, QA/QC

#85 fix: plantDetail 페이지 삭제
  src/app/(greeny)/plant/[id]/PlantDetail.tsx
Labels: 버그

#87 fix: 게시글 이미지 없을 때 메타데이터 에러 해결
  src/app/(greeny)/story/community/[id]/page.tsx
  src/app/(greeny)/story/diaries/[id]/page.tsx
Labels: 버그

#88 remove: 불필요한 패키지 및 파일 삭제
  package.json
  src/QueryProvider.tsx
  src/RecoilWrapper.tsx
  src/app/(greeny)/layout.tsx
  src/atoms/atoms.ts
  yarn.lock
Labels: 환경 설정

#91 fix: 북마크 데이터 memo 추가 및 메인페이지 metadata수정
  api/dbinit/team/data.js
  public/images/Checkbox_nor.svg
  src/app/(greeny)/(home)/page.tsx
  src/app/(greeny)/books/Books.module.scss
  src/app/(greeny)/story/community/[id]/edit/PostFormEdit.tsx
Labels: 버그, QA/QC

#93 docs: README 수정
  README.md
Labels: 문서 작업
